### ISSUE TITLE
Error when following README.md Getting Started

### ISSUE THREAD

**Issue by bjfish** [graalvm/sulong#106]
I get the following error when I follow the readme "Getting Started" section. Do I need to install this dependency locally?

Do you have a recommended way to install this dependency on Mac OSX? 

Thank you.

```
Exception in thread "main" java.lang.AssertionError: java.io.IOException: java.lang.UnsatisfiedLinkError: libgfortran.so.3
	at com.oracle.truffle.llvm.LLVM.evaluateFromSource(LLVM.java:144)
	at com.oracle.truffle.llvm.LLVM.executeMain(LLVM.java:123)
	at com.oracle.truffle.llvm.LLVM.main(LLVM.java:99)
Caused by: java.io.IOException: java.lang.UnsatisfiedLinkError: libgfortran.so.3
	at com.oracle.truffle.api.TruffleLanguage$AccessAPI.eval(TruffleLanguage.java:588)
	at com.oracle.truffle.api.impl.Accessor.eval(Accessor.java:163)
	at com.oracle.truffle.api.vm.PolyglotEngine$SPIAccessor.eval(PolyglotEngine.java:1177)
	at com.oracle.truffle.api.vm.PolyglotEngine.evalImpl(PolyglotEngine.java:541)
	at com.oracle.truffle.api.vm.PolyglotEngine.access$300(PolyglotEngine.java:106)
	at com.oracle.truffle.api.vm.PolyglotEngine$2.compute(PolyglotEngine.java:525)
	at com.oracle.truffle.api.vm.ComputeInExecutor.run(ComputeInExecutor.java:93)
	at com.oracle.truffle.api.vm.ComputeInExecutor.perform(ComputeInExecutor.java:83)
	at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:528)
	at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:464)
	at com.oracle.truffle.llvm.LLVM.evaluateFromSource(LLVM.java:141)
	... 2 more
Caused by: java.lang.UnsatisfiedLinkError: libgfortran.so.3
	at com.oracle.graal.truffle.hotspot.nfi.HotSpotNativeFunctionInterface.getLibraryHandle(HotSpotNativeFunctionInterface.java:71)
	at com.oracle.graal.truffle.hotspot.nfi.HotSpotNativeFunctionInterface.getLibraryHandle(HotSpotNativeFunctionInterface.java:39)
	at com.oracle.truffle.llvm.nativeint.NativeLookup.getNativeFunctionHandles(NativeLookup.java:93)
	at com.oracle.truffle.llvm.nativeint.NativeLookup.getLibraryHandles(NativeLookup.java:82)
	at com.oracle.truffle.llvm.nativeint.NativeLookup.uncachedGetNativeFunctionHandle(NativeLookup.java:171)
	at com.oracle.truffle.llvm.nativeint.NativeLookup.getNativeHandle(NativeLookup.java:151)
	at com.oracle.truffle.llvm.nodes.impl.base.LLVMContext.getNativeHandle(LLVMContext.java:74)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNode$LLVMUnresolvedCallNode.executeGeneric(LLVMCallNode.java:122)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallUnboxNodeFactory$LLVMI32CallUnboxNodeGen.executeI32(LLVMCallUnboxNodeFactory.java:188)
	at com.oracle.truffle.llvm.nodes.impl.vars.LLVMWriteNodeFactory$LLVMWriteI32NodeGen.executeVoid(LLVMWriteNodeFactory.java:189)
	at com.oracle.truffle.llvm.nodes.impl.others.LLVMBlockNode$LLVMBlockNoControlFlowNode.executeVoid(LLVMBlockNode.java:105)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMFunctionBodyNode.executeGeneric(LLVMFunctionBodyNode.java:49)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:63)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:443)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:303)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:291)
	at com.oracle.graal.truffle.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:206)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:69)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:60)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMGlobalRootNode.executeProgram(LLVMGlobalRootNode.java:104)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMGlobalRootNode.execute(LLVMGlobalRootNode.java:84)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:443)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:303)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:291)
	at com.oracle.graal.truffle.OptimizedCallTarget.call(OptimizedCallTarget.java:199)
	at com.oracle.truffle.llvm.nodes.impl.base.LLVMMainFunctionReturnValueRootNode$LLVMMainFunctionReturnNumberRootNode.execute(LLVMMainFunctionReturnValueRootNode.java:81)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:443)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:303)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:291)
	at com.oracle.graal.truffle.OptimizedCallTarget.call(OptimizedCallTarget.java:199)
	at com.oracle.truffle.api.TruffleLanguage$AccessAPI.eval(TruffleLanguage.java:584)
	... 12 more
```

**Comment by chrisseaton** [comment]
I think it's just `brew install gcc`, but you may have to tap something to do that. I can't remember - can you give it a go?

**Comment by mrigger** [comment]
Thanks for your interest in the project!

The error indicates that `libgfortran.so.3` could not be found. Sulong automatically links to this library to execute Fortran programs compiled by GCC+Dragonegg. Under Ubuntu, we install the `gfortran-4.6` package to get this library. To obtain a list of all external dependencies you can have a look at our [Travis configuration](https://github.com/graalvm/sulong/blob/master/.travis.yml) for Ubuntu.

If you just want to experiment with C files, you can change the [Mx file](https://github.com/graalvm/sulong/blob/4b394160139a9c9c2eed2da6d20c03fadc4e2403/mx.sulong/mx_sulong.py#L370) and let `getSearchPathOption` return an empty string.

Additionally, we should address this issue in:
- the README file, i.e., state the external dependencies
- the Travis configuration to provide a template of the external dependencies

**Comment by bjfish** [comment]
The following brew command errored for me on OSX.
`brew install gcc46`
https://github.com/Homebrew/homebrew-versions/issues/1056

So, I created the following vagrant file to try this on Ubuntu.

To get this to work, I had to have sulong project inside a folder with the vagrant folder because `mx build` cloned a bunch of projects into sulong's parent folder: graal-core, jvmci, and truffle.
```
project/Vagrantfile
project/sulong/
project/${cloned.projects}
```
I also had to run `mx build` with sudo due to folder permission errors:
`sudo mx build`

After, that I could run `mx su-run test.ll`

Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "hashicorp/precise64"
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
  end
 
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -y update
    sudo apt-get install python-software-properties -y
    sudo add-apt-repository -y ppa:mercurial-ppa/releases
    sudo add-apt-repository -y ppa:fkrull/deadsnakes
    sudo add-apt-repository -y ppa:webupd8team/java
    sudo apt-get -y update
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
    sudo apt-get install oracle-java8-installer -y
    sudo apt-get install oracle-java8-set-default -y
    sudo apt-get install git -y
    sudo apt-get install python2.7 -y
    sudo apt-get install python-pip -y
    sudo apt-get install mercurial -y
    sudo apt-get install gcc-4.6 -y
    sudo apt-get install gcc-4.6-plugin-dev -y
    sudo apt-get install gobjc++-4.6 -y
    sudo apt-get install g++-4.6 -y
    sudo apt-get install gfortran-4.6 -y
    sudo apt-get install libgmp3-dev -y
    sudo apt-get install llvm-3.3 -y
    sudo apt-get install build-essential -y
    sudo pip install astroid==1.1.0
    sudo pip install pylint==1.1.0
    pylint --version
    hg --version
    echo 'Cloning mx'
    git clone https://github.com/graalvm/mx
    echo 'Wget ecj'
    wget -o /dev/null http://ftp.halifax.rwth-aachen.de/eclipse//eclipse/downloads/drops4/R-4.5.1-201509040015/ecj-4.5.1.jar
    mv ecj-4.5.1.jar mx/ecj.jar
    export JDT=`pwd`/mx/ecj.jar
    wget -o /dev/null https://lafo.ssw.uni-linz.ac.at/slavefiles/gate/eclipse-jdk8-linux-x86_64.tar.gz
    tar -xzf eclipse-jdk8-linux-x86_64.tar.gz
    echo 'Finished adding dependencies'
    echo "export ECLIPSE_EXE=eclipse/eclipse" >> /home/vagrant/.bashrc
    echo "export DEFAULT_VM=server" >> /home/vagrant/.bashrc
    echo "export PATH=/home/vagrant/mx:$PATH" >> /home/vagrant/.bashrc
    echo "cd /vagrant" >> /home/vagrant/.bashrc
    echo 'Done'
  SHELL

end

```

**Comment by mrigger** [comment]
It's unfortunate that the installation didn't work on OSX. We have a hardcoded dependency on GCC 4.6, since Dragonegg [works best with this version](http://dragonegg.llvm.org/). However, GCC versions 4.5, 4.7, and 4.8 are also supported by Dragonegg. Can you install one of these versions with Homebrew? Then we could (and we should anyway) also allow other GCC versions in mx, e.g., by specifying an environment variable.

I will update the documentation that also other projects will be cloned into Sulong's sibling directories.

Do you have the permission error output of `mx build`? Usually, you should not need sudo rights to build.

Thanks a lot for helping us with your feedback and the Vagrantfile!

**Comment by bjfish** [comment]
I was able to do `brew install gcc48`  but `brew install gcc47` failed for me. 

I fixed the permission error by changing the clone in the Vagrantfile to `sudo -u vagrant git clone https://github.com/graalvm/mx` (also edited above).

**Comment by mrigger** [comment]
With #111 you can now specify the GCC command that Dragonegg uses. You can have a try by editing sulong/mx.sulong/env and adding the following environment variables:

```
SULONG_GCC=gcc48
SULONG_GPP=g++48
```

**Comment by mrigger** [comment]
@lukasstadler and me tried to get Sulong running on Mac. We had problems installing GCC with MacPorts, but eventually succeeded installing version 4.6. We found the following things:

- The [GCC](https://github.com/graalvm/sulong/blob/master/projects/com.oracle.truffle.llvm.tools/src/com/oracle/truffle/llvm/tools/GCC.java) class uses a hardcoded gcc-4.6 command. The reason for the duplication of the compilation logic in mx and on the Java side is described in #82. I will fix this to also use the environment variable instead.
- As described above we use hardcoded library names in the [mx file](https://github.com/graalvm/sulong/blob/4b394160139a9c9c2eed2da6d20c03fadc4e2403/mx.sulong/mx_sulong.py#L370). We could locally execute the tests by replacing the existing library paths with `-Dsulong.DynamicNativeLibraryPath=/opt/local/lib/libgcc/libgfortran.3.dylib:/opt/local/lib/libstdc++.6.dylib:/opt/local/lib/libgmp.10.dylib`. We fully qualified the paths, since the linker cannot find them (with [dlopen](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/dlopen.3.html)) otherwise. Probably, we should use an environment variable to override the shared library paths and set the above as default on Mac.
- We still could not execute all test cases, since some failed with an unsuccessful command to compile object files to executables with GCC. The object files already had an ELF header. We did not yet further investigate this issue.

**Comment by chrisseaton** [comment]
> You can have a try by editing sulong/mx.sulong/env and adding the following environment variables:

@mrigger when I try that with GCC 4.8 I get:

```
Downloading http://llvm.org/releases/3.2/dragonegg-3.2.src.tar.gz to /Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/dragonegg/dragonegg-3.2.src.tar.gz
 665450 bytes (100%)
Linking TargetInfo
Undefined symbols for architecture x86_64:
  "llvm::Triple::normalize[abi:cxx11](llvm::StringRef)", referenced from:
      _main in TargetInfo.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

I'm not sure what it is that's failing. Is it the Dragon Egg plugin itself?

**Comment by mrigger** [comment]
Yes, it is Dragonegg itself and it seems that linking some parts of LLVM to Dragonegg failed. 

Which mx command did you use? Can you ensure that the LLVM dependencies exist by downloading them (they should be downloaded automatically though) with `mx su-pullllvmbinaries`? It might also be worth to try with GCC 4.7 and GCC 4.6 and see if the same error occurs.

**Comment by chrisseaton** [comment]
```
$ SULONG_GCC=gcc-4.8 SULONG_GPP=g++-4.8 mx --vm server su-tests-gcc
Downloading http://llvm.org/releases/3.2/dragonegg-3.2.src.tar.gz to /Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/dragonegg/dragonegg-3.2.src.tar.gz
 665450 bytes (100%)
Linking TargetInfo
Undefined symbols for architecture x86_64:
  "llvm::Triple::normalize[abi:cxx11](llvm::StringRef)", referenced from:
      _main in TargetInfo.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [TargetInfo] Error 1
```

I also get the same thing with

```
$ SULONG_GCC=gcc-4.8 SULONG_GPP=g++-4.8 mx --vm server su-pulldragonegg
```

So I guess it's the install somehow that's breaking. Does it care what my system LLVM version is?

I also don't understand why it tries to download Dragonegg every time. Doesn't it cache it?

**Comment by chrisseaton** [comment]
I think we've broken this down into #113, #115 and #116, so I'll close this.
