### ISSUE TITLE
Interop can't handle TruffleObject as LLVMAddress

### ISSUE THREAD

**Issue by chrisseaton** [graalvm/sulong#196]
(#195 needed to see this problem)

My Ruby C extension API implementation has this code:

```c
static void *ruby_cext;

__attribute__((constructor))
void truffle_ruby_load() {
  ruby_cext = truffle_import("ruby_cext");
}
```

The import gives a `TruffleObject` and the assign to `ruby_cext` tries to execute `LLVMAddressStoreNode`, which executes `LVMAddressReadNode`, which tries to cast the `TruffleObject` to `LLVMAddress`.

```
java.lang.ClassCastException: com.oracle.graal.truffleom.a.c cannot be cast to com.oracle.truffle.llvm.types.LLVMAddress
	at com.oracle.truffle.llvm.nodes.impl.vars.LLVMReadNodeFactory$LLVMAddressReadNodeGen.executePointee(LLVMReadNodeFactory.java:442)
	at com.oracle.truffle.llvm.nodes.impl.memory.LLVMStoreNodeFactory$LLVMAddressStoreNodeGen.executeVoid(LLVMStoreNodeFactory.java:358)
	at com.oracle.truffle.llvm.nodes.impl.base.LLVMBasicBlockNode.executeGetSuccessorIndex(LLVMBasicBlockNode.java:63)
	at com.oracle.truffle.llvm.nodes.impl.others.LLVMBlockNode$LLVMBlockControlFlowNode.executeGeneric(LLVMBlockNode.java:71)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:63)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:503)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:365)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:351)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:339)
	at com.oracle.graal.truffle.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:254)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:70)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:61)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNode$LLVMFunctionCallChain.doDirect(LLVMCallNode.java:296)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNodeFactory$LLVMFunctionCallChainNodeGen$DirectNode_.execute(LLVMCallNodeFactory.java:195)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNodeFactory$LLVMFunctionCallChainNodeGen$BaseNode_.acceptAndExecute(LLVMCallNodeFactory.java:113)
	at com.oracle.truffle.api.dsl.internal.SpecializationNode.uninitialized(SpecializationNode.java:407)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNodeFactory$LLVMFunctionCallChainNodeGen$UninitializedNode_.execute(LLVMCallNodeFactory.java:153)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNodeFactory$LLVMFunctionCallChainNodeGen.executeDispatch(LLVMCallNodeFactory.java:74)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNode$LLVMFunctionCallChainStartNode.executeGeneric(LLVMCallNode.java:238)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNode$LLVMUnresolvedCallNode.executeGeneric(LLVMCallNode.java:153)
	at com.oracle.truffle.llvm.nodes.base.LLVMExpressionNode.executeVoid(LLVMExpressionNode.java:44)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallUnboxNode$LLVMVoidCallUnboxNode.executeVoid(LLVMCallUnboxNode.java:128)
	at com.oracle.truffle.llvm.nodes.impl.others.LLVMStaticInitsBlockNode.execute(LLVMStaticInitsBlockNode.java:61)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:503)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:365)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:351)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:339)
	at com.oracle.graal.truffle.OptimizedCallTarget.call(OptimizedCallTarget.java:244)
	at com.oracle.truffle.llvm.LLVM$1.lambda$1(LLVM.java:116)
	at com.oracle.truffle.llvm.SulongLibrary.readContents(SulongLibrary.java:88)
	at com.oracle.truffle.llvm.LLVM$1.parse(LLVM.java:102)
	at com.oracle.truffle.llvm.nodes.impl.base.LLVMLanguage.parse(LLVMLanguage.java:98)
	at com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:436)
	at org.jruby.truffle.language.loader.FeatureLoader.ensureCExtImplementationLoaded(FeatureLoader.java:262)
```

To reproduce, build JRuby master, set `SULONG_DIR`, and run `JRUBY_OPTS=-Xtruffle.exceptions.print_java=true jt test cexts`.

If you want to modify the C extension API implementation, it's in `truffle/src/main/c/cext`. Compile with `bin/jruby bin/jruby-cext-c truffle/src/main/c/cext`.

**Comment by grimmerm** [comment]
There is a fundamental problem:
`static void *ruby_cext;` is a global variable. Sulong stores global variables in the **native memory**.
References to TruffleObjects (or any Java object) cannot be stored in the native memory, hence, this test fails.
can you make `*ruby_cext` a local variable? that would solve your problem.

if not, I can try to come up with some kind of fallback for this case.

**Comment by mrigger** [comment]
Did #219 solve this issue for now? If yes, we can close the issue.

**Comment by chrisseaton** [comment]
Worked around with #219. I wouldn't say the problem is solved, but the is also a long term problem that will be tackled by new research projects, so I will close.
