### ISSUE TITLE
Support rdtsc instruction in inline assembler (multiple return registers)

### ISSUE THREAD

**Issue by lxp** [graalvm/sulong#375]
Support the following inline assemble snipped on amd64 (as used by argon2 benchmark):

``` c
static uint64_t rdtsc(void) {
    uint64_t rax, rdx;
    __asm__ __volatile__("rdtsc" : "=a"(rax), "=d"(rdx) : :);
    return (rdx << 32) | rax;
}
```

To reproduce, run argon2 benchmark: `mx su-bench-argon2`

```
-- line 1 col 2: invalid InlineAssembly
Exception in thread "main" java.lang.AssertionError: STRUCT
    at com.oracle.truffle.llvm.parser.factories.NodeFactoryFacadeImpl.createInlineAssemblerExpression(NodeFactoryFacadeImpl.java:388)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.visitFunctionCall(LLVMVisitor.java:742)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.visitFunctionCall(LLVMVisitor.java:1036)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.visitNamedMiddleInstruction(LLVMVisitor.java:782)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.visitMiddleInstruction(LLVMVisitor.java:703)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.visitInstruction(LLVMVisitor.java:691)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.visitBasicBlock(LLVMVisitor.java:670)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.getFunctionBlockStatements(LLVMVisitor.java:536)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.visitFunction(LLVMVisitor.java:516)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.visit(LLVMVisitor.java:297)
    at com.oracle.truffle.llvm.parser.impl.LLVMVisitor.getMain(LLVMVisitor.java:263)
    at com.oracle.truffle.llvm.LLVM.parseString(LLVM.java:254)
    at com.oracle.truffle.llvm.LLVM$1.lambda$parse$1(LLVM.java:142)
    at com.oracle.truffle.llvm.SulongLibrary.readContents(SulongLibrary.java:88)
    at com.oracle.truffle.llvm.LLVM$1.parse(LLVM.java:137)
    at com.oracle.truffle.llvm.nodes.impl.base.LLVMLanguage.parse(LLVMLanguage.java:101)
    at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.eval(TruffleLanguage.java:574)
    at com.oracle.truffle.api.vm.PolyglotEngine.evalImpl(PolyglotEngine.java:565)
    at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:532)
    at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:469)
    at com.oracle.truffle.llvm.LLVM.evaluateFromSource(LLVM.java:312)
    at com.oracle.truffle.llvm.LLVM.executeMain(LLVM.java:290)
    at com.oracle.truffle.llvm.LLVM.main(LLVM.java:238)
```

**Comment by mrigger** [comment]
Fixed by #589.
