### ISSUE TITLE
NullPointerException when using while(1) in the Bitcode Parser

### ISSUE THREAD

**Issue by pointhi** [graalvm/sulong#475]
```
Exception in thread "main" java.lang.NullPointerException
	at com.oracle.truffle.llvm.nodes.impl.vars.LLVMWriteNode.getSourceSection(LLVMWriteNode.java:79)
	at com.oracle.truffle.api.nodes.Node.getEncapsulatingSourceSection(Node.java:152)
	at com.oracle.truffle.llvm.nodes.impl.base.LLVMBasicBlockNode.executeGetSuccessorIndex(LLVMBasicBlockNode.java:101)
	at com.oracle.truffle.llvm.nodes.impl.others.LLVMBlockNode$LLVMBlockControlFlowNode.executeGeneric(LLVMBlockNode.java:77)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:112)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:220)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:212)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:203)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:187)
	at com.oracle.graal.truffle.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:171)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:70)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:61)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMGlobalRootNode.executeIteration(LLVMGlobalRootNode.java:114)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMGlobalRootNode.execute(LLVMGlobalRootNode.java:90)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:220)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:212)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:203)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:187)
	at com.oracle.graal.truffle.OptimizedCallTarget.call(OptimizedCallTarget.java:165)
	at com.oracle.truffle.llvm.nodes.impl.base.LLVMMainFunctionReturnValueRootNode$LLVMMainFunctionReturnNumberRootNode.execute(LLVMMainFunctionReturnValueRootNode.java:81)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:220)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:212)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:203)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:187)
	at com.oracle.graal.truffle.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:171)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:70)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:61)
	at com.oracle.truffle.api.vm.PolyglotEngine$PolyglotEvalRootNode.executeImpl(PolyglotEngine.java:767)
	at com.oracle.truffle.api.vm.PolyglotEngine$PolyglotRootNode.execute(PolyglotEngine.java:729)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:220)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:212)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:203)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:187)
	at com.oracle.graal.truffle.OptimizedCallTarget.call(OptimizedCallTarget.java:165)
	at com.oracle.truffle.api.vm.PolyglotEngine.evalImpl(PolyglotEngine.java:548)
	at com.oracle.truffle.api.vm.PolyglotEngine.evalImpl(PolyglotEngine.java:528)
	at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:469)
	at com.oracle.truffle.llvm.LLVM.evaluateFromSource(LLVM.java:350)
	at com.oracle.truffle.llvm.LLVM.executeMain(LLVM.java:328)
	at com.oracle.truffle.llvm.LLVM.main(LLVM.java:272)
```

```c
int main(void)
{
    while(1);
    return 0;
}
```

**Comment by mrigger** [comment]
Solved by #476. Can you please confirm @pointhi?
