### ISSUE TITLE
 java.lang.IllegalStateException: LLVM_38

### ISSUE THREAD

**Issue by pointhi** [graalvm/sulong#669]
When I run for example the sulong38 testsuite, I get the following stacktrace:

```
Caused by: java.io.IOException: Error while trying to parse /home/thomas/JKU/java-llvm-ir-builder-dev/sulong/cache/tests/sulong/c/truffle-c/controlTest/while1/while1_clang_v38_O0.bc
    at com.oracle.truffle.llvm.LLVM$1.parse(LLVM.java:94)
    at com.oracle.truffle.llvm.runtime.LLVMLanguage.parse(LLVMLanguage.java:105)
    at com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:391)
    at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.parseForLanguage(TruffleLanguage.java:907)
    ... 48 more
Caused by: java.lang.IllegalStateException: LLVM_38
    at com.oracle.truffle.llvm.parser.listeners.IRVersionController.setVersion(IRVersionController.java:121)
    at com.oracle.truffle.llvm.parser.listeners.Identification.record(Identification.java:46)
    at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:345)
    at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.abbreviatedRecord(LLVMScanner.java:165)
    at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanNext(LLVMScanner.java:158)
    at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.parse(LLVMScanner.java:97)
    at com.oracle.truffle.llvm.parser.BitcodeParserResult.getFromSource(BitcodeParserResult.java:69)
    at com.oracle.truffle.llvm.parser.LLVMParserRuntime.parse(LLVMParserRuntime.java:85)
    at com.oracle.truffle.llvm.LLVM.parseBitcodeFile(LLVM.java:240)
    at com.oracle.truffle.llvm.LLVM.access$000(LLVM.java:61)
    at com.oracle.truffle.llvm.LLVM$1.parse(LLVM.java:103)
    at com.oracle.truffle.llvm.LLVM$1.parse(LLVM.java:92)
    ... 51 more
```

From what I found out, it is caused by the following code, which includes for example a comparison of a String and a enum:

```java
    public void setVersion(String versionStr) {
        IRVersion newVersion = getVersion(versionStr);
        if (version == IRVersion.DEFAULT || version == newVersion) {
            version = newVersion;
        } else {
            throw new IllegalStateException(version.toString());
        }
    }

    private static IRVersion getVersion(String versionStr) {
        for (IRVersion v : IRVersion.values()) {
            if (v.isVersion(versionStr)) {
                return v;
            }
        }
        return IRVersion.DEFAULT;
    }
```

I think the code needs changed to:

```java
    public void setVersion(String versionStr) {
        version = getVersion(versionStr);
    }

    private static IRVersion getVersion(String versionStr) {
        for (IRVersion v : IRVersion.values()) {
            if (v.isVersion(versionStr)) {
                return v;
            }
        }
        return IRVersion.DEFAULT;
    }
```

**Comment by pointhi** [comment]
solved
