### ISSUE TITLE
Sulong cannot parse llvm vectors of pointers

### ISSUE THREAD

**Issue by mikehearn** [graalvm/sulong#743]
I used wllvm to build a bytecode file for the coreutils `du` utility. The unified bytecode file runs OK when using the lli utility from LLVM 4 itself but prints nothing when using Sulong. I'm using the `lli` that comes with the latest GraalVM. Playing with the flags a bit gets me this error:

```
mike@littlegreen ~/S/g/v/coreutils-8.27> ../graalvm-0.26/bin/lli --print-result --jvm src/du.bc
org.graalvm.polyglot.PolyglotException: java.lang.RuntimeException: java.io.IOException: Error while trying to parse /Users/mike/Source/graal/vm/coreutils-8.27/src/du.bc
	at com.oracle.truffle.llvm.parser.listeners.Types.record(Types.java:149)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:343)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.unabbreviatedRecord(LLVMScanner.java:363)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanNext(LLVMScanner.java:152)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.parse(LLVMScanner.java:96)
	at com.oracle.truffle.llvm.parser.BitcodeParserResult.getFromSource(BitcodeParserResult.java:66)
	at com.oracle.truffle.llvm.parser.LLVMParserRuntime.parse(LLVMParserRuntime.java:89)
	at com.oracle.truffle.llvm.Runner.parseBitcodeFile(Runner.java:175)
	at com.oracle.truffle.llvm.Runner.parse(Runner.java:63)
	at com.oracle.truffle.llvm.Sulong.parse(Sulong.java:79)
	at com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:487)
	at com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:766)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.parse(TruffleLanguage.java:1381)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:370)
	at org.graalvm.polyglot.Context.eval(Context.java:145)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.d(stripped:161)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.a(stripped:33)
	at com.oracle.graalvm.launcher.a.a(stripped:70)
	at com.oracle.graalvm.launcher.a.a(stripped:21)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.main(stripped:24)
```

So it seems the bytecode file can't be read somehow (wrong version of LLVM?) but this error isn't printed unless I use the --print-result flag for some reason.

How should I debug this? lli doesn't seem to have any flags that can be used to enable logging and there is no info on debugging in the docs directory.

**Comment by mikehearn** [comment]
Here's the real stack trace:

```
Caused by: java.lang.ClassCastException: com.oracle.truffle.llvm.runtime.types.PointerType cannot be cast to com.oracle.truffle.llvm.runtime.types.PrimitiveType
	at com.oracle.truffle.llvm.parser.listeners.Types.record(Types.java:149)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:343)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.unabbreviatedRecord(LLVMScanner.java:363)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanNext(LLVMScanner.java:152)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.parse(LLVMScanner.java:96)
	at com.oracle.truffle.llvm.parser.BitcodeParserResult.getFromSource(BitcodeParserResult.java:66)
	at com.oracle.truffle.llvm.parser.LLVMParserRuntime.parse(LLVMParserRuntime.java:89)
	at com.oracle.truffle.llvm.Runner.parseBitcodeFile(Runner.java:179)
	at com.oracle.truffle.llvm.Runner.parse(Runner.java:69)
	... 8 more
```

The issue here seems simple enough - it's trying to parse a vector of i8*. Sulong does not allow that.

The LLVM documentation says that a vector type requires a size and an "underlying primitive type", however, the table of examples it gives shows that pointers are also allowed:

https://llvm.org/docs/LangRef.html#vector-type

Sulong apparently expects that primitive types != pointer types. I've heard before that LLVM tends to mix up integers and pointers at various places, this seems to be one of those times.

**Comment by mikehearn** [comment]
I started implementing this myself, which was an enjoyable tour around the codebase, then noticed that support for this was merged on Friday! I updated and indeed hit the next problem, which I will file a PR for shortly.
