### ISSUE TITLE
Would be helpful to have tagged releases

### ISSUE THREAD

**Issue by mikehearn** [graalvm/sulong#744]
So far I've tried a couple of times at different dates and been unable to compile or run Sulong from git. The problem seems to be version skew between different components. Currently I'm getting an exception that indicates some sort of internal API change.

But more generally, it's not really clear to me how to assemble a working system. For instance Graal/Truffle can build against JDK9, but Sulong doesn't, it needs a Java 8. So I tried to build it against a GraalVM (what readme calls labsjdk) and that helped, but it still doesn't start.

I suspect this would be easier if I could check out a Sulong/Graal/Truffle git tag and use it with a specific version of the GraalVM.

```
Exception in thread "main" java.lang.InternalError
	at com.oracle.truffle.api.Truffle$1.run(Truffle.java:120)
	at com.oracle.truffle.api.Truffle$1.run(Truffle.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.oracle.truffle.api.Truffle.initRuntime(Truffle.java:61)
	at com.oracle.truffle.api.Truffle.<clinit>(Truffle.java:49)
	at com.oracle.truffle.api.impl.Accessor.<clinit>(Accessor.java:515)
	at com.oracle.truffle.api.TruffleLanguage.<clinit>(TruffleLanguage.java:1342)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.truffle.api.Truffle$1.run(Truffle.java:117)
	... 6 more
Caused by: java.util.ServiceConfigurationError: com.oracle.truffle.api.TruffleRuntimeAccess: Provider org.graalvm.compiler.truffle.hotspot.HotSpotTruffleRuntimeAccess not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at jdk.vm.ci.services.Services.loadSingle(Services.java:147)
	... 11 more
```

**Comment by grimmerm** [comment]
Sulong uses mx (the build tool for Truffle/Graal projects, https://github.com/graalvm/mx), which automatically downloads the right Truffle/Graal version (specified in mx.sulong/suite.py).
As described in the README.md, pls download labsjdk1.8.0_121-jvmci-0.29 and set JAVA_HOME.

Te README instructions should work for macOS, Ubuntu, and Fedora (there is no Windows support).

In general, Sulong uses a pre-merge gate, so every TIP is fully tested on our CI (cf travis.yml for system configuration) and there should be no TIP that does not build/fail our tests.

**Comment by grimmerm** [comment]
Sulong releases are part of GrralVM, which you can download as a binary from http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html

**Comment by mikehearn** [comment]
Ah, I'm sorry. I got confused because I thought GraalVM was the new name for the LabsJDK. When I clicked the link and saw GraalVM download, I figured the README wasn't up to date. But scrolling to the bottom I see a separate download called LabsJDK. I'll try again with that.

**Comment by mikehearn** [comment]
With the LabsJDK instead of GraalVM JDK I was able to get it building and debuggable, thanks.
