### ISSUE TITLE
Bitcode for fish shell fails to parse

### ISSUE THREAD

**Issue by mikehearn** [graalvm/sulong#747]
After building fish at commit ba53242b266a0901b176ef7f7de872dc6b5e9956 with wllvm, I get this when trying to execute it:

```
org.graalvm.polyglot.PolyglotException: java.lang.RuntimeException: java.io.IOException: Error while trying to parse /Users/mike/Source/graal/sulong/fish-shell/fish.bc
	at com.oracle.truffle.llvm.parser.listeners.Function.getElementPointerType(Function.java:1010)
	at com.oracle.truffle.llvm.parser.listeners.Function.createGetElementPointer(Function.java:810)
	at com.oracle.truffle.llvm.parser.listeners.Function.record(Function.java:267)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:343)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.abbreviatedRecord(LLVMScanner.java:164)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanNext(LLVMScanner.java:157)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.parse(LLVMScanner.java:96)
	at com.oracle.truffle.llvm.parser.BitcodeParserResult.getFromSource(BitcodeParserResult.java:66)
	at com.oracle.truffle.llvm.parser.LLVMParserRuntime.parse(LLVMParserRuntime.java:89)
	at com.oracle.truffle.llvm.Runner.parseBitcodeFile(Runner.java:179)
	at com.oracle.truffle.llvm.Runner.parse(Runner.java:69)
	at com.oracle.truffle.llvm.Sulong.parse(Sulong.java:79)
	at com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:489)
	at com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:773)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.parse(TruffleLanguage.java:1443)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:530)
	at org.graalvm.polyglot.Context.eval(Context.java:145)
	at com.oracle.truffle.llvm.Sulong.executeMain(Sulong.java:133)
	at com.oracle.truffle.llvm.Sulong.main(Sulong.java:117)
Original Internal Error: 
java.lang.RuntimeException: java.io.IOException: Error while trying to parse /Users/mike/Source/graal/sulong/fish-shell/fish.bc
	at com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:777)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.parse(TruffleLanguage.java:1443)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:530)
	at org.graalvm.polyglot.Context.eval(Context.java:145)
	at com.oracle.truffle.llvm.Sulong.executeMain(Sulong.java:133)
	at com.oracle.truffle.llvm.Sulong.main(Sulong.java:117)
Caused by: java.io.IOException: Error while trying to parse /Users/mike/Source/graal/sulong/fish-shell/fish.bc
	at com.oracle.truffle.llvm.Runner.parse(Runner.java:109)
	at com.oracle.truffle.llvm.Sulong.parse(Sulong.java:79)
	at com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:489)
	at com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:773)
	... 5 more
Caused by: java.lang.IllegalStateException: Cannot index type: com.oracle.truffle.llvm.parser.listeners.Types$UnresolvedPointeeType@22c
	at com.oracle.truffle.llvm.parser.listeners.Function.getElementPointerType(Function.java:1010)
	at com.oracle.truffle.llvm.parser.listeners.Function.createGetElementPointer(Function.java:810)
	at com.oracle.truffle.llvm.parser.listeners.Function.record(Function.java:267)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:343)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.abbreviatedRecord(LLVMScanner.java:164)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanNext(LLVMScanner.java:157)
	at com.oracle.truffle.llvm.parser.scanner.LLVMScanner.parse(LLVMScanner.java:96)
	at com.oracle.truffle.llvm.parser.BitcodeParserResult.getFromSource(BitcodeParserResult.java:66)
	at com.oracle.truffle.llvm.parser.LLVMParserRuntime.parse(LLVMParserRuntime.java:89)
	at com.oracle.truffle.llvm.Runner.parseBitcodeFile(Runner.java:179)
	at com.oracle.truffle.llvm.Runner.parse(Runner.java:69)
	... 8 more
```

**Comment by mikehearn** [comment]
This is probably related to #748

**Comment by mikehearn** [comment]
Your PR fixes this issue successfully.

**Comment by mikehearn** [comment]
Next issue is a `com.oracle.truffle.llvm.runtime.SulongRuntimeException: <4 x i32> ZERO_EXTENSION` so I'll close this on the assumption the PR gets merged.

**Comment by jkreindl** [comment]
@mikehearn Can you also close #748. That was the actual target of my PR.
