### ISSUE TITLE
sulong not exiting from va_start call

### ISSUE THREAD

**Issue by noahdesu** [graalvm/sulong#835]
I've traced sulong execution to `va_start` where it is not exiting for a particular invocation. Some calls do work correctly. Here is the case that is not working:

```
test_func(int op, ...) {
  va_list ap;
  va_start(ap, op);
}

struct Forward *data = ...;
static void fp(void *arg1, int arg2, const char *arg3) {..}

test_func(100, fp, data);
```

**Comment by jkreindl** [comment]
Shouldn't your function call `va_end` before returning? I'm not very familiar with vararg handling, but at least that is suggested [here](http://www.cplusplus.com/reference/cstdarg/va_start/).

**Comment by noahdesu** [comment]
Yes, va_end does need to be called. The example above isn't complete, it's taken from a much larger project, which does properly called va_end. I

The point I'm trying to make, but I don't think I did good job of making, is that I've traced the thread into `va_start` and it exits at that point. I'm using a crude printf tracing strategy. Is there any debugging tools for sulong?

There have been a few other issues related to varargs n the past, too:

#716 
#711 

I'll try to extract a reproducible example from the code base I'm playing with. Thanks.

**Comment by jkreindl** [comment]
Thanks for the clarification. Sulong supports source-level debugging, see the [docs](https://github.com/graalvm/sulong/blob/master/docs/DEBUGGING.md) for details on how to use it. Just remember to compile your bitcode file with `-g` to include debug information.

**Comment by noahdesu** [comment]
I recompiled with `-g`. When I start up `lli` as described in the debug docs. It spits out the URL and waits. When I open the debug chrome URL it just reports disconnection, and back at the terminal the program exits. Any clues?

**Comment by noahdesu** [comment]
@jkreindl thanks a lot for taking the time to work through this issue with me. I've made a little progress, not debugging the original issue, but debugging the debugging the problem :)

So I was able to get the debugger working with the test program from the README:

```
#include <stdio.h>
int main() {
  printf("Hello from Sulong!");
  return 0;
}
```

Then I was able to reproduce the silent exit by calling a function that isn't linked in, for example:

```
#include <stdio.h>
extern void nolink(void);
int main() {
  printf("Hello from Sulong!");
  nolink();
  printf("won't be printed");
  return 0;
}
```

will print `Hello from Sulong`, but not `won't be printed`. I certainly don't expect it to print `won't be printed`, but I did expect some sort of loud noise and errors to be made at some point, hence the silent error.

This is trivially resolvable for the toy example, but the program I'm trying to run with Sulong is quite large. It's unknown to me what deep hole of linking dependencies I need to go look through. Any way Sulong can help with this?

**Comment by jkreindl** [comment]
Thanks for finding an example. The new launcher seems to just swallow any exceptions per default and terminates the VM with 255 as exit value. You can still get a stacktrace with the error if you invoke Sulong with the `--print-result` argument, e.g. `mx lli --print-result test.c`.

@rschatz Is that really a sensible default? At the very least we should document this behavior in the README.

**Comment by noahdesu** [comment]
@jkreindl ok this is really great, thanks a lot. using that `--print-result` arg i was able to create a minimal reproducer of the original issue that prompted this ticket. here is the test program:

Calls a variable argument function with a function pointer as a parameter, extracts the function pointer with varargs, and invokes the target function:

```
#include <stdarg.h>
#include <stdio.h>

#define OP 10

static void func(void *arg, int val, const char *msg)
{
  printf("in func: %p/%d/%s\n", arg, val, msg);
}

static void varfunc(int op, ...)
{
  va_list ap;

  va_start(ap, op);

  if (op == OP) {
    typedef void (*func_t)(void *, int, const char *);
    func_t fp = va_arg(ap, func_t);
    void *data = va_arg(ap, void *);
    fp(data, OP, "my_op");
  }

  va_end(ap);
}

int main(int argc, char **argv)
{
  const void *data = (void*)0xdeadbeef;
  varfunc(OP, func, data);
  return 0;
}
```

This is the expected behavior:

```
[nwatkins@bourbon graal]$ clang -O1 -o test test.c
[nwatkins@bourbon graal]$ ./test 
in func: 0xdeadbeef/10/my_op
```

And this is the output with `--print-result`

```
org.graalvm.polyglot.PolyglotException: com.oracle.truffle.llvm.runtime.SulongRuntimeException: AssertionError function@137 '@func'

C stack trace:
	 varfunc in test.c:15:3 (LLVM IR Function varfunc in test.bc in Block {id: 0 name: implicit1})
	 main in test.c:31:3 (LLVM IR Function main in test.bc in Block {id: 0 name: implicit2})
	 LLVM IR Function @_start in libsulong.bc in Block {id: 4 name: %sw.bb}

	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at com.oracle.truffle.llvm.runtime.SulongRuntimeException.<init>(SulongRuntimeException.java:42)
	at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.executeStatements(LLVMBasicBlockNode.java:117)
	at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:92)
	at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:75)
	at <llvm> varfunc(Unknown)
	at <llvm> main(test.c:31:505)
	at <llvm> @_start(libsulong.bc:@_start:1:0-19)
	at <llvm> null(Unknown)
	at <llvm> null(Unknown)
	at org.graalvm.polyglot.Context.eval(Context.java:162)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.a(stripped:170)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.launch(stripped:33)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:104)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:52)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.main(stripped:24)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:170)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original Internal Error: 
com.oracle.truffle.llvm.runtime.SulongRuntimeException: AssertionError function@137 '@func'

C stack trace:
	 varfunc in test.c:15:3 (LLVM IR Function varfunc in test.bc in Block {id: 0 name: implicit1})
	 main in test.c:31:3 (LLVM IR Function main in test.bc in Block {id: 0 name: implicit2})
	 LLVM IR Function @_start in libsulong.bc in Block {id: 4 name: %sw.bb}

	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at com.oracle.truffle.llvm.runtime.SulongRuntimeException.<init>(SulongRuntimeException.java:42)
	at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.executeStatements(LLVMBasicBlockNode.java:117)
	at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:92)
	at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:75)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:192)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:81)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:65)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:91)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:132)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:93)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNode.doDirectCached(LLVMLookupDispatchNode.java:70)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeAndSpecialize(LLVMLookupDispatchNodeGen.java:134)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeDispatch(LLVMLookupDispatchNodeGen.java:97)
	at com.oracle.truffle.llvm.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:73)
	at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.executeStatements(LLVMBasicBlockNode.java:98)
	at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:92)
	at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:75)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:192)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:81)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:65)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:91)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:132)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:93)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNode.doDirectCached(LLVMLookupDispatchNode.java:70)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeAndSpecialize(LLVMLookupDispatchNodeGen.java:134)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeDispatch(LLVMLookupDispatchNodeGen.java:97)
	at com.oracle.truffle.llvm.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:73)
	at com.oracle.truffle.llvm.runtime.nodes.api.LLVMExpressionNode.executeI32(LLVMExpressionNode.java:105)
	at com.oracle.truffle.llvm.nodes.others.LLVMValueProfilingNodeFactory$LLVMI32ProfiledValueNodeGen.executeI32(LLVMValueProfilingNodeFactory.java:280)
	at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI32NodeGen.executeGeneric(LLVMWriteNodeFactory.java:348)
	at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.executeStatements(LLVMBasicBlockNode.java:98)
	at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:92)
	at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:75)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:192)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:81)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:65)
	at com.oracle.truffle.llvm.nodes.func.LLVMGlobalRootNode.execute(LLVMGlobalRootNode.java:72)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:192)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:81)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:65)
	at com.oracle.truffle.llvm.nodes.base.LLVMMainFunctionReturnValueRootNode$LLVMMainFunctionReturnNumberRootNode.execute(LLVMMainFunctionReturnValueRootNode.java:82)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:185)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:764)
	at org.graalvm.polyglot.Context.eval(Context.java:162)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.a(stripped:170)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.launch(stripped:33)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:104)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:52)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.main(stripped:24)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:170)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: java.lang.AssertionError: function@137 '@func'
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at java.lang.AssertionError.<init>(AssertionError.java:58)
	at java.lang.AssertionError.<init>(AssertionError.java:74)
	at com.oracle.truffle.llvm.nodes.intrinsics.llvm.x86.LLVMX86_64VAStart.getVarArgArea(LLVMX86_64VAStart.java:171)
	at com.oracle.truffle.llvm.nodes.intrinsics.llvm.x86.LLVMX86_64VAStart.computeOverflowArgAreaSize(LLVMX86_64VAStart.java:191)
	at com.oracle.truffle.llvm.nodes.intrinsics.llvm.x86.LLVMX86_64VAStart.vaStart(LLVMX86_64VAStart.java:243)
	at com.oracle.truffle.llvm.nodes.intrinsics.llvm.x86.LLVMX86_64VAStartNodeGen.executeAndSpecialize(LLVMX86_64VAStartNodeGen.java:46)
	at com.oracle.truffle.llvm.nodes.intrinsics.llvm.x86.LLVMX86_64VAStartNodeGen.executeGeneric(LLVMX86_64VAStartNodeGen.java:34)
	at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.executeStatements(LLVMBasicBlockNode.java:98)
	... 69 more
Caused by: com.oracle.truffle.api.TruffleStackTrace$LazyStackTrace
Caused by: com.oracle.truffle.api.TruffleStackTrace
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at com.oracle.truffle.api.TruffleStackTrace.<init>(TruffleStackTrace.java:50)
	at com.oracle.truffle.api.TruffleStackTrace.fillIn(TruffleStackTrace.java:170)
	at com.oracle.truffle.api.TruffleStackTrace.addStackFrameInfo(TruffleStackTrace.java:233)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.onThrowable(TruffleLanguage.java:1866)
	at com.oracle.truffle.api.impl.TVMCI.onThrowable(TVMCI.java:178)
	at org.graalvm.compiler.truffle.runtime.GraalTVMCI.onThrowable(GraalTVMCI.java:112)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:250)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:192)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:81)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:65)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:91)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:132)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:93)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNode.doDirectCached(LLVMLookupDispatchNode.java:70)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeAndSpecialize(LLVMLookupDispatchNodeGen.java:134)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeDispatch(LLVMLookupDispatchNodeGen.java:97)
	at com.oracle.truffle.llvm.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:73)
	at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.executeStatements(LLVMBasicBlockNode.java:98)
	at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:92)
	at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:75)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:192)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:81)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:65)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:91)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:132)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:93)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNode.doDirectCached(LLVMLookupDispatchNode.java:70)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeAndSpecialize(LLVMLookupDispatchNodeGen.java:134)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeDispatch(LLVMLookupDispatchNodeGen.java:97)
	at com.oracle.truffle.llvm.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:73)
	at com.oracle.truffle.llvm.runtime.nodes.api.LLVMExpressionNode.executeI32(LLVMExpressionNode.java:105)
	at com.oracle.truffle.llvm.nodes.others.LLVMValueProfilingNodeFactory$LLVMI32ProfiledValueNodeGen.executeI32(LLVMValueProfilingNodeFactory.java:280)
	at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI32NodeGen.executeGeneric(LLVMWriteNodeFactory.java:348)
	at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.executeStatements(LLVMBasicBlockNode.java:98)
	at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:92)
	at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:75)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:192)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:81)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:65)
	at com.oracle.truffle.llvm.nodes.func.LLVMGlobalRootNode.execute(LLVMGlobalRootNode.java:72)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:192)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:81)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:65)
	at com.oracle.truffle.llvm.nodes.base.LLVMMainFunctionReturnValueRootNode$LLVMMainFunctionReturnNumberRootNode.execute(LLVMMainFunctionReturnValueRootNode.java:82)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at com.oracle.svm.enterprise.truffle.SubstrateEnterpriseOptimizedCallTarget.doInvoke(stripped:174)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:185)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:764)
	at org.graalvm.polyglot.Context.eval(Context.java:162)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.a(stripped:170)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.launch(stripped:33)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:104)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:52)
	at com.oracle.graalvm.launcher.llvm.LLVMLauncher.main(stripped:24)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:170)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
```

**Comment by jkreindl** [comment]
Great, thanks for the test! @pointhi @pekd  or @rschatz since I know next ot nothing about vararg handling in LLVM/Sulong, could one of you please take a look at this?

**Comment by pekd** [comment]
Since the exception occurs [here](https://github.com/graalvm/sulong/blob/4b6de58019844c1ffdfaeea261912a8d6f2c377b/projects/com.oracle.truffle.llvm.nodes/src/com/oracle/truffle/llvm/nodes/intrinsics/llvm/x86/LLVMX86_64VAStart.java#L171), it looks like the case for a function pointer argument is just missing.

**Comment by pointhi** [comment]
@pekd: You are correct. Function Pointers seems to use a different Class. They should go to ```VarArgArea.GP_AREA``` like it's done with ```LLVMAddress```.

**Comment by noahdesu** [comment]
Oh, this is great. Thank you for fixing this. I'm wondering how long I might expect to wait for a new release with this fix to drop on the download site?

**Comment by jkreindl** [comment]
New GraalVM releases usually come out at the end of the month. There is an irregular release scheduled very soon, but it probably won't contain this fix yet.
